### ISSUE TITLE
Error running command line helper `wdp`

### ISSUE THREAD

**Issue by nicc777** [nicc777/py_workdocs_prep#12]
Error:

```shell
>wdp
Traceback (most recent call last):
  File "d:\tmp\venv\lib\site-packages\pkg_resources\__init__.py", line 2419, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'py_workdocs_prep' has no attribute 'start'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\tmp\venv\Scripts\wdp-script.py", line 11, in <module>
    load_entry_point('py-workdocs-prep==0.1.0', 'console_scripts', 'wdp')()
  File "d:\tmp\venv\lib\site-packages\pkg_resources\__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "d:\tmp\venv\lib\site-packages\pkg_resources\__init__.py", line 2793, in load_entry_point
    return ep.load()
  File "d:\tmp\venv\lib\site-packages\pkg_resources\__init__.py", line 2411, in load
    return self.resolve()
  File "d:\tmp\venv\lib\site-packages\pkg_resources\__init__.py", line 2421, in resolve
    raise ImportError(str(exc))
ImportError: module 'py_workdocs_prep' has no attribute 'start'
```

**Comment by nicc777** [comment]
Fixed and released version release-0.1.1
