### ISSUE TITLE
Uncaught Exception

### ISSUE THREAD

**Issue by nicc777** [nicc777/py_workdocs_prep#13]
Output:
```shell
C:\Users\xxxxxxx\Dropbox>wdp
Starting in "C:\Users\xxxxxxx\Dropbox"
Traceback (most recent call last):
  File "C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37\Scripts\wdp-script.py", line 11, in <module>
    load_entry_point('py-workdocs-prep==0.3.1', 'console_scripts', 'wdp')()
  File "c:\users\xxxxxxx\appdata\local\programs\python\python37\lib\site-packages\py_workdocs_prep\py_workdocs_prep.py", line 274, in start
    recurse_dir(root_dir=start)
  File "c:\users\xxxxxxx\appdata\local\programs\python\python37\lib\site-packages\py_workdocs_prep\py_workdocs_prep.py", line 154, in recurse_dir
    recurse_dir(item_full_path, directories_to_delete_if_found=directories_to_delete_if_found)
  File "c:\users\xxxxxxx\appdata\local\programs\python\python37\lib\site-packages\py_workdocs_prep\py_workdocs_prep.py", line 154, in recurse_dir
    recurse_dir(item_full_path, directories_to_delete_if_found=directories_to_delete_if_found)
  File "c:\users\xxxxxxx\appdata\local\programs\python\python37\lib\site-packages\py_workdocs_prep\py_workdocs_prep.py", line 154, in recurse_dir
    recurse_dir(item_full_path, directories_to_delete_if_found=directories_to_delete_if_found)
  [Previous line repeated 4 more times]
  File "c:\users\xxxxxxx\appdata\local\programs\python\python37\lib\site-packages\py_workdocs_prep\py_workdocs_prep.py", line 145, in recurse_dir
    for item in os.listdir(root_dir):
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\\Users\\xxxxxxx\\Dropbox\\.....'
```

The total length of the problematic file was 270 characters (as it was displayed). The maximum path length is 260 characters (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN).

The cause of the exception cannot be solved, but the script must be able to handle the exception.

**Comment by nicc777** [comment]
Tested and done
